services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    ports:
      - "80:8110"
    networks:
      - web-tier
      - api-tier
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    depends_on:
      - service
      - redis
      - postgres
    networks:
      - api-tier
      - internal-tier

  service:
    build:
      context: .
      dockerfile: service.Dockerfile
    restart: always
    depends_on:
      - postgres
    networks:
      - internal-tier

  redis:
    image: redis
    restart: always
    command: ["redis-server", "--save", "30", "1"]
    networks:
      - internal-tier
    volumes:
      - redis-data:/data

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres:rw
    networks:
      - internal-tier

volumes:
  redis-data:
  postgres_data:

networks:
  web-tier:
  api-tier:
  internal-tier: