services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    ports:
      - "80:8110"
    environment:
      WEB_API_ADDR: "http://api:9090"
    networks:
      - web-tier
      - api-tier
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - "9090:9090"
    environment:
      API_DSN: "host=postgres user=postgres password=my_pass dbname=shortlink port=5432 sslmode=disable"
      API_CACHE_ADDR: "redis:6379"
      API_SERVICE_ADDR: "service:9091"
    depends_on:
      - service
      - redis
      - postgres
    networks:
      - api-tier
      - service-tier

  service:
    build:
      context: .
      dockerfile: service.Dockerfile
    restart: always
    environment:
      SERVICE_DSN: "host=postgres user=postgres password=my_pass dbname=shortlink port=5432 sslmode=disable"
    depends_on:
      - postgres
    networks:
      - service-tier

  redis:
    image: redis
    restart: always
    networks:
      - api-tier

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres:rw
    networks:
      - service-tier

volumes:
  postgres_data:

networks:
  web-tier:
  api-tier:
  service-tier: