services:
  web:
    image: userxat/shortlink-web
    restart: always
    ports:
      - 80:8110
    networks:
      - web-tier
      - service-tier
      - cache-tier
    depends_on:
      - service
      - cache

  service:
    image: userxat/shortlink-service
    restart: always
    networks:
      - service-tier
      - redis-tier
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    networks:
      - api-tier

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres:rw
    networks:
      - service-tier

volumes:
  postgres_data:

networks:
  web-tier:
  api-tier:
  service-tier: