apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shortlink-web
  template:
    metadata:
      labels:
        app: shortlink-web
    spec:
      containers:
        - name: shortlink-web
          image: userxat/shortlink-web
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8110
---
apiVersion: v1
kind: Service
metadata:
  name: shortlink-web
spec:
  type: LoadBalancer
  selector:
    app: shortlink-web
  ports:
    - port: 8110
      targetPort: 8110
